# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  functionsproject: '**/MapR.Functions.csproj'
  vuefolder: '**/MapR.Vue'

  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
 - stage: Build
   jobs:
   - job: Build
     steps:
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '$(functionsproject)'
          configuration: '$(buildConfiguration)'
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(vuefolder)'
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(vuefolder)'
          customCommand: 'npm run build'